"""The flat error envelope, the per-code constants, and the exception handlers.

DATABASE_SETUP.md Part 3.0. Written BEFORE the first route, deliberately:
retrofitting an error envelope means auditing every ``raise`` in the codebase.

Every non-2xx response from every route has exactly this body::

    {"error_code": ..., "message": ..., "retryable": ..., "request_id": ...}

FastAPI's default ``{"detail": ...}`` -- and in particular the *list* body it
produces for ``RequestValidationError`` with status 422 -- must never escape.
422 is not in the client's error taxonomy (it would surface as a raw
"Server error (422).") and the default body leaks the internal field paths of
the request model.

``request_id`` is generated by ``RequestIdMiddleware``, held in a ``ContextVar``,
set as the ``X-Request-Id`` header on ALL responses including 2xx, and injected
into the envelope by every handler here.
"""

from __future__ import annotations

import logging
import uuid
from contextvars import ContextVar
from typing import Any, Final

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from app.models.enums import ErrorCode
from app.models.responses import ErrorEnvelope

logger = logging.getLogger("tennisform.api")

REQUEST_ID_HEADER: Final[str] = "X-Request-Id"

_request_id_var: ContextVar[str] = ContextVar("request_id", default="")


def current_request_id() -> str:
    """The id of the request being served, or ``""`` outside a request."""
    return _request_id_var.get()


def new_request_id() -> str:
    """A fresh correlation id. 32 hex chars, matching the Part 3.0 example."""
    return uuid.uuid4().hex


# ---------------------------------------------------------------------------
# Per-code constants (DATABASE_SETUP.md Part 3.0.1).
#
# `retryable` is a per-ErrorCode CONSTANT, not a runtime guess (Part 6 item 18).
# It is defined for all 20 members, including the job-only ones, because those
# codes still appear inside the nested `AnalysisError` of a 200 poll response
# and that object carries `retryable` too.
# ---------------------------------------------------------------------------

ERROR_RETRYABLE: Final[dict[ErrorCode, bool]] = {
    ErrorCode.INVALID_REQUEST: False,
    ErrorCode.AUTH_INVALID_TOKEN: False,
    ErrorCode.STORAGE_PATH_FORBIDDEN: False,
    ErrorCode.ANALYSIS_NOT_FOUND: False,
    ErrorCode.OBJECT_NOT_FOUND: False,
    ErrorCode.FILE_TOO_LARGE: False,
    ErrorCode.UNSUPPORTED_CONTENT_TYPE: False,
    ErrorCode.CALIBRATION_INVALID: False,
    ErrorCode.QUEUE_FULL: True,
    ErrorCode.STORAGE_UNAVAILABLE: True,
    ErrorCode.UNSUPPORTED_CODEC: False,
    ErrorCode.DECODE_FAILED: False,
    ErrorCode.NO_VIDEO_STREAM: False,
    ErrorCode.VIDEO_TOO_SHORT: False,
    ErrorCode.VIDEO_TOO_LONG: False,
    ErrorCode.NO_POSE_DETECTED: False,
    ErrorCode.POSE_QUALITY_TOO_LOW: False,
    ErrorCode.CONTACT_NOT_FOUND: False,
    ErrorCode.WORKER_LOST: True,
    ErrorCode.INTERNAL_ERROR: True,
}

#: HTTP status per code. Contains ONLY the codes Part 3.0.1 gives an HTTP
#: column; the ten "job-only" codes are absent on purpose -- they never appear
#: in an HTTP error envelope, only inside the `error` object of a 200 poll
#: response. `http_status_for` treats a job-only code reaching the HTTP path as
#: the bug it is.
ERROR_HTTP_STATUS: Final[dict[ErrorCode, int]] = {
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.UNSUPPORTED_CONTENT_TYPE: 400,
    ErrorCode.CALIBRATION_INVALID: 400,
    ErrorCode.AUTH_INVALID_TOKEN: 401,
    ErrorCode.STORAGE_PATH_FORBIDDEN: 403,
    ErrorCode.ANALYSIS_NOT_FOUND: 404,
    ErrorCode.OBJECT_NOT_FOUND: 404,
    ErrorCode.FILE_TOO_LARGE: 413,
    ErrorCode.QUEUE_FULL: 429,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.STORAGE_UNAVAILABLE: 503,
}

#: Default human-readable text per code. Safe to show: never a stack trace,
#: never a storage path, never another user's id.
ERROR_MESSAGES: Final[dict[ErrorCode, str]] = {
    ErrorCode.INVALID_REQUEST: "That request could not be understood.",
    ErrorCode.AUTH_INVALID_TOKEN: "Your session is not valid. Sign in and try again.",
    ErrorCode.STORAGE_PATH_FORBIDDEN: "That video does not belong to this account.",
    ErrorCode.ANALYSIS_NOT_FOUND: "That analysis could not be found.",
    ErrorCode.OBJECT_NOT_FOUND: "That video could not be found. Upload it again.",
    ErrorCode.FILE_TOO_LARGE: "That video is too large. Record a shorter clip.",
    ErrorCode.UNSUPPORTED_CONTENT_TYPE: "That video format is not supported.",
    ErrorCode.CALIBRATION_INVALID: "The court calibration was not valid.",
    ErrorCode.QUEUE_FULL: "The analyzer is busy. Try again in a moment.",
    ErrorCode.STORAGE_UNAVAILABLE: "Video storage is unavailable. Try again shortly.",
    ErrorCode.UNSUPPORTED_CODEC: "That video uses a format we cannot read.",
    ErrorCode.DECODE_FAILED: "That video could not be read.",
    ErrorCode.NO_VIDEO_STREAM: "That file contains no video.",
    ErrorCode.VIDEO_TOO_SHORT: "That clip is too short to analyze.",
    ErrorCode.VIDEO_TOO_LONG: "That clip is too long to analyze.",
    ErrorCode.NO_POSE_DETECTED: "No player could be seen in the clip.",
    ErrorCode.POSE_QUALITY_TOO_LOW: "The player was not clear enough to analyze.",
    ErrorCode.CONTACT_NOT_FOUND: "No clear ball-strike was found in the clip.",
    ErrorCode.WORKER_LOST: "The analysis was interrupted. Try again.",
    ErrorCode.INTERNAL_ERROR: "Something went wrong on our end.",
}


def is_retryable(code: ErrorCode) -> bool:
    """Per-code constant retryability."""
    return ERROR_RETRYABLE[code]


def http_status_for(code: ErrorCode) -> int:
    """HTTP status for a code that is raised on the HTTP path.

    A job-only code has no HTTP status by design. Reaching here with one means a
    route raised something only a background job should raise, so it is logged
    and degraded to 500 rather than crashing the handler that is already
    handling an error.
    """
    status = ERROR_HTTP_STATUS.get(code)
    if status is None:
        logger.error("job-only ErrorCode %s raised on the HTTP path; sending 500", code.value)
        return 500
    return status


def default_message_for(code: ErrorCode) -> str:
    return ERROR_MESSAGES[code]


class ApiError(Exception):
    """The project's own HTTP error. Carries an ``ErrorCode``, not a ``detail``.

    Preferred over ``HTTPException`` everywhere in this codebase, because the
    envelope needs a machine-readable code and ``HTTPException`` has nowhere to
    put one.
    """

    def __init__(
        self,
        error_code: ErrorCode,
        *,
        message: str | None = None,
        http_status: int | None = None,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.error_code: ErrorCode = error_code
        self.message: str = message if message is not None else default_message_for(error_code)
        self.http_status: int = http_status if http_status is not None else http_status_for(error_code)
        self.retryable: bool = is_retryable(error_code)
        self.headers: dict[str, str] = dict(headers or {})
        super().__init__(f"{error_code.value}: {self.message}")


def envelope_response(
    error_code: ErrorCode,
    message: str,
    http_status: int,
    *,
    headers: dict[str, str] | None = None,
) -> JSONResponse:
    """Build the one and only error body shape."""
    request_id = current_request_id() or new_request_id()
    envelope = ErrorEnvelope(
        error_code=error_code,
        message=message,
        retryable=is_retryable(error_code),
        request_id=request_id,
    )
    out_headers: dict[str, str] = {REQUEST_ID_HEADER: request_id}
    out_headers.update(headers or {})
    return JSONResponse(
        status_code=http_status,
        content=envelope.model_dump(mode="json"),
        headers=out_headers,
    )


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------


class RequestIdMiddleware:
    """Pure-ASGI middleware assigning and echoing ``X-Request-Id``.

    Pure ASGI rather than ``BaseHTTPMiddleware`` on purpose: ``BaseHTTPMiddleware``
    runs the downstream app in its own task, so the ``ContextVar`` set there is
    not visible to Starlette's ``ServerErrorMiddleware``, which sits UPSTREAM and
    is what invokes the ``Exception`` handler. Staying in the same task context
    keeps ``current_request_id()`` correct in every handler, including the 500 one.

    The ``ContextVar`` is intentionally never reset: each request runs in its own
    task context, so there is nothing to leak into, and resetting on the way out
    would blank the id exactly when an exception is propagating past us.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = new_request_id()
        _request_id_var.set(request_id)

        async def send_with_request_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers: list[tuple[bytes, bytes]] = list(message.get("headers", []))
                key = REQUEST_ID_HEADER.lower().encode("latin-1")
                if not any(name.lower() == key for name, _ in headers):
                    headers.append((key, request_id.encode("latin-1")))
                message = {**message, "headers": headers}
            await send(message)

        await self.app(scope, receive, send_with_request_id)


# ---------------------------------------------------------------------------
# Handlers
# ---------------------------------------------------------------------------


async def api_error_handler(request: Request, exc: Exception) -> JSONResponse:
    """``ApiError`` -> the flat envelope with its own code and status."""
    assert isinstance(exc, ApiError)
    logger.info(
        "api_error request_id=%s code=%s status=%s path=%s",
        current_request_id(),
        exc.error_code.value,
        exc.http_status,
        request.url.path,
    )
    return envelope_response(exc.error_code, exc.message, exc.http_status, headers=exc.headers)


async def validation_error_handler(request: Request, exc: Exception) -> JSONResponse:
    """``RequestValidationError`` -> **400 invalid_request**, never a bare 422.

    This is the handler that gets forgotten. Without it a Pydantic failure on
    ``CreateAnalysisRequest`` or ``UploadTicketRequest`` returns FastAPI's 422
    with a list body under ``detail``, which (a) is not in the client's error
    taxonomy and (b) leaks the internal field paths of the request model.

    The per-field detail is logged against ``request_id``, not returned.
    """
    detail: Any = exc.errors() if isinstance(exc, RequestValidationError) else str(exc)
    logger.info(
        "validation_error request_id=%s path=%s detail=%s",
        current_request_id(),
        request.url.path,
        detail,
    )
    return envelope_response(
        ErrorCode.INVALID_REQUEST,
        default_message_for(ErrorCode.INVALID_REQUEST),
        http_status_for(ErrorCode.INVALID_REQUEST),
    )


async def http_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Net for anything Starlette raises internally: unknown path (404), 405, ...

    Not a licence to raise ``HTTPException`` from a route -- routes raise
    ``ApiError``. This exists so a 404 on a mistyped URL still comes back in the
    envelope rather than as ``{"detail": "Not Found"}``.
    """
    assert isinstance(exc, StarletteHTTPException)
    if exc.status_code == 401:
        code = ErrorCode.AUTH_INVALID_TOKEN
    elif exc.status_code == 404:
        code = ErrorCode.ANALYSIS_NOT_FOUND if "/analyses/" in request.url.path else ErrorCode.INVALID_REQUEST
    elif 400 <= exc.status_code < 500:
        code = ErrorCode.INVALID_REQUEST
    else:
        code = ErrorCode.INTERNAL_ERROR
    headers = dict(exc.headers or {})
    return envelope_response(code, default_message_for(code), exc.status_code, headers=headers)


async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Anything unhandled -> 500 ``internal_error`` with a generic message.

    The real exception is logged against ``request_id``; it never reaches the
    client.
    """
    logger.exception(
        "unhandled_exception request_id=%s path=%s", current_request_id(), request.url.path
    )
    return envelope_response(
        ErrorCode.INTERNAL_ERROR,
        default_message_for(ErrorCode.INTERNAL_ERROR),
        http_status_for(ErrorCode.INTERNAL_ERROR),
    )


def register_exception_handlers(app: FastAPI) -> None:
    """Install all four handlers. Called before any router is included."""
    app.add_exception_handler(ApiError, api_error_handler)
    app.add_exception_handler(RequestValidationError, validation_error_handler)
    app.add_exception_handler(StarletteHTTPException, http_exception_handler)
    app.add_exception_handler(Exception, unhandled_exception_handler)


#: Reusable OpenAPI ``responses=`` fragment so the generated schema advertises
#: the envelope instead of FastAPI's default error schema (Part 3.0). The
#: Flutter models are read off that schema by a human and a wrong schema costs
#: a day.
def openapi_errors(*codes: ErrorCode) -> dict[int | str, dict[str, Any]]:
    out: dict[int | str, dict[str, Any]] = {}
    for code in codes:
        status = http_status_for(code)
        out.setdefault(
            status,
            {"model": ErrorEnvelope, "description": ""},
        )
        description = out[status]["description"]
        out[status]["description"] = f"{description}, {code.value}".lstrip(", ")
    return out
